FFW controller
loudinthecloud/pytorch-ntm pull request #3
Opened 2018-03-18 00:51 UTC by gbmarc1

Added FeedFoward network controller class
A parameters have been added to choose controller type

2018-03-18 19:23 UTC, loudinthecloud requested changes
Seems good, thanks for the contribution!

One thing that is missing is validation that it is working and converging. How does it perform?

2018-03-18 19:23 UTC, loudinthecloud commented on .gitignore
> +.idea/*
This is better placed in the global .gitignore file

2018-03-18 19:23 UTC, loudinthecloud commented on tasks/copytask.py
> +    controller_type = attrib(default='LSTM', convert=str)
Please make it an Enum, how can I tell what are the valid options?

2018-03-18 19:23 UTC, loudinthecloud commented on ntm/aio.py
> +            controller = FFWController(num_inputs + M * num_heads, controller_size, controller_layers)
Please use:

`CONTROLLERS = {
    'LSTM': LSTMController,
    'FFW': FFWController
}`

Then the code has no repetitions (DRY)...

2018-03-19 03:22 UTC, gbmarc1 commented
Thank you for the PRs. I will correct as requested. 
I will also validate the modification with both Tasks.
I am planning to add the vanilla LSTM as the paper. I will submit all those modifications when I will be done.

2018-03-19 03:22 UTC, closed without merging

2018-03-19 09:41 UTC, loudinthecloud commented
Thanks, sounds great!